### PR TITLE
Prevent Zombie Annotations on page unload

### PR DESCRIPTION
**Pull request by rsimon**
## In this PR

We have taken various measures to prevent the creation of "zombie annotations" - annotations that have no comment (or tag) and hence remain displayed in draft state forever (or until the original creator re-opens them and adds a comment/tag).

Technically, Recogito deletes annotation if the user de-selects it, and it has no annotation bodies. 

One situation that would still lead to zombie annotations was the following:
- the user creates a new annotation
- without adding a comment or tag, the user closes the browser tab

This PR adds a listener to the page that will delete an empty, open annotation, if the user leaves the page.

Cf. issue https://github.com/performant-software/cove-recogito/issues/21

### CODE REVIEW

**Review by lwjameson — APPROVED** [review]
Nice.

**Comment by SteveMarvin** [comment]
My logins don't seem to work for this preview.

**Comment by lwjameson** [comment]
I see all of your various usernames there.  I assume you are getting 401's?

**Comment by rsimon** [comment]
I have added an additional measure, attempting to prevent zombie annotations. (In the [@recogito/annotorious-supabase package](https://github.com/recogito/annotorious-supabase/commit/bb6470d2198075adebbfc972a4c535b2da04e397). It's now in the `develop` branch, i.e. not on the Netlify staging site yet!)

- Instead of using the Supabase JavaScript SDK, the call to archive annotations is now made through the REST interface directly.
- I'm setting the `keepalive` flag in the request, which instructs the browser to keep the request alive even after the page closes.

I'm not sure if this can address __all__ cases. (Behavior might differ between closing tab and actually closing the browser.) But from the client, I think this is pretty much as far as I can go. (FWIW: `navigator.sendBeacon` is said to be more robust than `fetch` + `keepAlive`. But the latter option does not seem to support adding custom HTTP headers, which we need for Supabase auth.

**Pull request merged**
